services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      WP_TEST_DISABLE_MAIL: ${WP_TEST_DISABLE_MAIL:-1}
    ports:
      - "8100:80"
    volumes:
      - wp_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/members-for-kofi
    networks:
      - wpnet

  db:
    image: mysql:lts
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wp}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wp}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wp}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
    user: "33:33" # www-data
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WP_TEST_SITE_URL: ${WP_TEST_SITE_URL:-http://localhost:8100}
      WP_ADMIN_USER: ${WP_ADMIN_USER:-admin}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD:-admin}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL:-admin@example.com}
      WP_TEST_DISABLE_MAIL: ${WP_TEST_DISABLE_MAIL:-1}
    working_dir: /var/www/html
    volumes:
      - wp_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/members-for-kofi
    networks:
      - wpnet

volumes:
  wp_data:
  db_data:

networks:
  wpnet:
